<?php

return [
    'notification_time' => env('DIGEST_NOTIFICATION_TIME', '08:00'),
    'timezone' => env('DIGEST_TIMEZONE', config('app.timezone')),
    'articles_per_subject' => (int) env('DIGEST_ARTICLES_PER_SUBJECT', 5),
    'retrieval_candidates' => 30,
    'interest_decay_factor' => 0.98,
    'embedding_model' => env('DIGEST_EMBEDDING_MODEL', 'text-embedding-3-small'),
    'embedding_dimensions' => (int) env('DIGEST_EMBEDDING_DIMENSIONS', 1536),
    'ranking_model' => env('DIGEST_RANKING_MODEL', 'composer-2.5'),
    'cursor_api_key' => env('CURSOR_API_KEY'),
    'cursor_api_base_url' => env('CURSOR_API_BASE_URL', 'https://api.cursor.com/v1'),
    'table_prefix' => 'rd_',
    'queue' => env('DIGEST_QUEUE', 'default'),
    'telegram' => [
        'enabled' => filter_var(env('DIGEST_TELEGRAM_ENABLED', false), FILTER_VALIDATE_BOOL),
        'bot_token' => env('DIGEST_TELEGRAM_BOT_TOKEN'),
        'chat_id' => env('DIGEST_TELEGRAM_CHAT_ID'),
    ],
    'interaction_weights' => [
        'impression' => -0.5,
        'opened' => 1,
        'finished_reading' => 3,
        'saved' => 5,
        'liked' => 5,
        'disliked' => -5,
        'shared' => 8,
        'dismissed' => -5,
        'rated' => 0,
        'rated_positive' => 4,
        'rated_negative' => -6,
    ],
    'content_retention_days' => (int) env('DIGEST_CONTENT_RETENTION_DAYS', 90),
];
